### PR TITLE
Add a single create script to make life easier

### PR DESCRIPTION
**Pull request by vujita**
Just thought this maybe useful

### CODE REVIEW

**Comment by JamieCrisman** [comment]
Not certain, because I never poked at this part of the project, but aren't all the migrations supposed to handle this?

this would be another file to maintain if/when anything changes.

**Comment by austinpray** [comment]
Hey @vujita! 

Thank you for taking the time to put this PR together. Jamie is right, the sum of all the migrations gives you a db with this structure. The migrations are preferable because it gives you a db with a state that can be added to and rolled back. The migrations will also transform existing data.

We plan on making a little vagrant box that will automate the database creation and project setup. That might make all this easier anyway.

**Comment by vujita** [comment]
Hi, I only threw this in there because I found it a bit confusing. The readme describes a schema and migrations show create/rollback scripts, however they were not obviously ordered and I didn't see any main entry point that would handle script loading order

Also, when I read the migration scripts it seemed that the tables were dropped. Wouldn't that wipe all data from the db?

**Comment by austinpray** [comment]
Ah. Ok I see your confusion. We are using https://github.com/db-migrate/node-db-migrate to automate the db migrations. You should be able to run "db-migrate up" and all the migrations will be run in succession and it will be noted in the db that those migrations were run. 

I'll update the readme

**Comment by austinpray** [comment]
@vujita made things even simpler: https://github.com/UTD-CRSS/exploreapollo-api/tree/master/db

**Pull request closed without merging**
